// Copyright 2026 Victor Niharra <vniharrafe@gmail.com>
// SPDX-License-Identifier: agpl

// Command lifecyclegen writes the human and machine mirrors of the Go lifecycle
// registry.
//
//	go generate ./internal/lifecycle   # or: make lifecycle-generate
//	make generated-check               # check mode; writes nothing
//
// Generation is deterministic: the output is sorted, carries no timestamp, no
// absolute path and no map-iteration order, performs no network access, and is
// byte-identical across clean checkouts. Check mode never writes, so it can run
// in CI against a read-only tree and still leave `git status` clean.
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"jul/internal/lifecycle"
)

func main() {
	out := flag.String("out", "docs", "directory that receives the generated artifacts")
	check := flag.Bool("check", false, "compare the generated bytes with the files on disk and write nothing")
	flag.Parse()

	if err := run(*out, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(outDir string, check bool) error {
	artifacts, err := lifecycle.RenderArtifacts()
	if err != nil {
		return fmt.Errorf("lifecyclegen: render: %w", err)
	}

	var stale []string
	for _, rel := range lifecycle.ArtifactPaths {
		want := artifacts[rel]
		path := filepath.Join(outDir, filepath.FromSlash(rel))

		if check {
			got, err := os.ReadFile(path)
			if err != nil {
				if errors.Is(err, os.ErrNotExist) {
					stale = append(stale, rel+" (missing)")
					continue
				}
				return fmt.Errorf("lifecyclegen: read %s: %w", rel, err)
			}
			if string(got) != string(want) {
				stale = append(stale, rel)
			}
			continue
		}

		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("lifecyclegen: create directory for %s: %w", rel, err)
		}
		if err := os.WriteFile(path, want, 0o644); err != nil {
			return fmt.Errorf("lifecyclegen: write %s: %w", rel, err)
		}
	}

	if len(stale) > 0 {
		return fmt.Errorf(
			"lifecyclegen: generated lifecycle artifacts are stale: %v\n"+
				"    the Go lifecycle registry changed without regenerating its mirrors.\n"+
				"    run: %s",
			stale, lifecycle.RegenerateCommand)
	}
	return nil
}
