// Copyright 2026 Victor Niharra <vniharrafe@gmail.com>
// SPDX-License-Identifier: agpl

// Command configcontractgen writes the generated configuration contract
// artifacts: docs/generated/config.schema.json, config-metadata.json and
// config-reference.md (ADR 0019 §21-23).
//
//	go generate ./internal/configcontract   # or: make config-contract-generate
//	make generated-check                    # check mode; writes nothing
//
// Generation is deterministic: sorted, no timestamp, no absolute path, no
// map-iteration order, no network access, byte-identical across clean
// checkouts. Check mode never writes, so it can run in CI against a
// read-only tree and still leave `git status` clean.
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"jul/internal/configcontract"
)

func main() {
	out := flag.String("out", "docs", "directory that receives the generated artifacts")
	check := flag.Bool("check", false, "compare the generated bytes with the files on disk and write nothing")
	valueContract := flag.String("value-contract", "docs/config-value-contract.json", "path to the audited value-contract document")
	schemaGo := flag.String("schema-go", "internal/config/schema.go", "path to the Go configuration schema source")
	flag.Parse()

	if err := run(*out, *valueContract, *schemaGo, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(outDir, valueContractPath, schemaGoPath string, check bool) error {
	vc, err := configcontract.LoadValueContract(valueContractPath)
	if err != nil {
		return fmt.Errorf("configcontractgen: %w", err)
	}
	comments, err := configcontract.LoadFieldComments(schemaGoPath)
	if err != nil {
		return fmt.Errorf("configcontractgen: %w", err)
	}
	contract, err := configcontract.Build(configcontract.Sources{ValueContract: vc, Comments: comments})
	if err != nil {
		return fmt.Errorf("configcontractgen: %w", err)
	}
	artifacts, err := configcontract.RenderArtifacts(contract)
	if err != nil {
		return fmt.Errorf("configcontractgen: render: %w", err)
	}

	var stale []string
	for _, rel := range configcontract.ArtifactPaths {
		want := artifacts[rel]
		path := filepath.Join(outDir, filepath.FromSlash(rel))

		if check {
			got, err := os.ReadFile(path)
			if err != nil {
				if errors.Is(err, os.ErrNotExist) {
					stale = append(stale, rel+" (missing)")
					continue
				}
				return fmt.Errorf("configcontractgen: read %s: %w", rel, err)
			}
			if string(got) != string(want) {
				stale = append(stale, rel)
			}
			continue
		}

		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("configcontractgen: create directory for %s: %w", rel, err)
		}
		if err := os.WriteFile(path, want, 0o644); err != nil {
			return fmt.Errorf("configcontractgen: write %s: %w", rel, err)
		}
	}

	if len(stale) > 0 {
		return fmt.Errorf(
			"configcontractgen: generated configuration-contract artifacts are stale: %v\n"+
				"    a schema, lifecycle, value-contract or description source changed without regenerating its mirrors.\n"+
				"    run: %s",
			stale, configcontract.RegenerateCommand)
	}
	return nil
}
