// Copyright 2026 Victor Niharra <vniharrafe@gmail.com>
// SPDX-License-Identifier: agpl

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"jul/internal/apicontract"
)

func artifactPath(dir string) string {
	return filepath.Join(dir, filepath.FromSlash(apicontract.ArtifactPath))
}

// TestWriteThenCheckRoundTrips is the generator's contract in one test: what it
// writes is what check mode accepts, so `make api-contract-generate` followed by
// `make generated-check` is always green.
func TestWriteThenCheckRoundTrips(t *testing.T) {
	dir := t.TempDir()

	if err := run(dir, false); err != nil {
		t.Fatalf("write: %v", err)
	}
	got, err := os.ReadFile(artifactPath(dir))
	if err != nil {
		t.Fatalf("the generator wrote nothing: %v", err)
	}
	want, err := apicontract.Generate()
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if string(got) != string(want) {
		t.Fatal("the written bytes differ from the generated bytes")
	}

	if err := run(dir, true); err != nil {
		t.Fatalf("check mode rejected the bytes it had just written: %v", err)
	}
}

// TestCheckModeWritesNothing. The gate runs in CI against a tree that must stay
// clean, and a check that repairs what it is checking cannot fail.
func TestCheckModeWritesNothing(t *testing.T) {
	dir := t.TempDir()

	if err := run(dir, true); err == nil {
		t.Fatal("check mode passed against an empty directory")
	}
	if _, err := os.Stat(artifactPath(dir)); !os.IsNotExist(err) {
		t.Fatal("check mode created the artifact it was asked only to compare")
	}

	if err := run(dir, false); err != nil {
		t.Fatalf("write: %v", err)
	}
	stale := []byte("{\n  \"openapi\": \"3.1.0\"\n}\n")
	if err := os.WriteFile(artifactPath(dir), stale, 0o644); err != nil {
		t.Fatalf("write stale artifact: %v", err)
	}
	if err := run(dir, true); err == nil {
		t.Fatal("check mode accepted a stale artifact")
	}
	after, err := os.ReadFile(artifactPath(dir))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if string(after) != string(stale) {
		t.Fatal("check mode rewrote the stale artifact instead of reporting it")
	}
}

// TestStaleErrorsNameTheRemedy. A drift failure that does not say how to fix it
// costs every contributor the same lookup.
func TestStaleErrorsNameTheRemedy(t *testing.T) {
	dir := t.TempDir()

	missing := run(dir, true)
	if missing == nil {
		t.Fatal("a missing artifact was accepted")
	}
	if !strings.Contains(missing.Error(), "missing") {
		t.Errorf("the missing-artifact error does not say it is missing: %v", missing)
	}
	if !strings.Contains(missing.Error(), apicontract.RegenerateCommand) {
		t.Errorf("the error does not name the regeneration command: %v", missing)
	}

	if err := os.MkdirAll(filepath.Dir(artifactPath(dir)), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(artifactPath(dir), []byte("stale"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	drift := run(dir, true)
	if drift == nil {
		t.Fatal("a stale artifact was accepted")
	}
	if !strings.Contains(drift.Error(), apicontract.RegenerateCommand) {
		t.Errorf("the error does not name the regeneration command: %v", drift)
	}
	if !strings.Contains(drift.Error(), "never hand-edited") {
		t.Errorf("the error does not say the artifact is generated: %v", drift)
	}
}

// TestWriteCreatesTheOutputDirectory: the generator is run against a fresh
// checkout and against docs/generated, which may not exist yet.
func TestWriteCreatesTheOutputDirectory(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "output")
	if err := run(dir, false); err != nil {
		t.Fatalf("write into a missing directory: %v", err)
	}
	if _, err := os.Stat(artifactPath(dir)); err != nil {
		t.Fatalf("the artifact was not created: %v", err)
	}
}

// TestAnUnreadableArtifactIsReportedNotTreatedAsStale. Telling an operator to
// regenerate when the real problem is a permission or an I/O error sends them
// to the wrong fix.
func TestAnUnreadableArtifactIsReportedNotTreatedAsStale(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("running as root: file mode does not deny access")
	}
	dir := t.TempDir()
	if err := run(dir, false); err != nil {
		t.Fatalf("write: %v", err)
	}
	path := artifactPath(dir)
	if err := os.Chmod(path, 0o000); err != nil {
		t.Skipf("cannot make the artifact unreadable on this platform: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(path, 0o644) })

	err := run(dir, true)
	if err == nil {
		t.Skip("the platform ignored the file mode")
	}
	if strings.Contains(err.Error(), apicontract.RegenerateCommand) {
		t.Fatalf("an I/O failure was reported as staleness: %v", err)
	}
	if !strings.Contains(err.Error(), "read") {
		t.Fatalf("the error does not identify itself as a read failure: %v", err)
	}
}

// TestWriteFailsWhenTheOutputPathIsNotADirectory covers the remaining failure
// arm: the generator reports rather than panics.
func TestWriteFailsWhenTheOutputPathIsNotADirectory(t *testing.T) {
	dir := t.TempDir()
	blocker := filepath.Join(dir, "generated")
	if err := os.WriteFile(blocker, []byte("not a directory"), 0o644); err != nil {
		t.Fatalf("write blocker: %v", err)
	}
	if err := run(dir, false); err == nil {
		t.Fatal("writing under a non-directory succeeded")
	}
}

// TestWriteFailsWhenTheArtifactIsNotWritable reaches the write arm specifically,
// after the directory has been created successfully.
func TestWriteFailsWhenTheArtifactIsNotWritable(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("running as root: file mode does not deny writes")
	}
	dir := t.TempDir()
	if err := run(dir, false); err != nil {
		t.Fatalf("write: %v", err)
	}
	path := artifactPath(dir)
	if err := os.Chmod(path, 0o400); err != nil {
		t.Skipf("cannot make the artifact read-only on this platform: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(path, 0o644) })

	err := run(dir, false)
	if err == nil {
		t.Skip("the platform ignored the file mode")
	}
	if !strings.Contains(err.Error(), "write") {
		t.Fatalf("the error does not identify itself as a write failure: %v", err)
	}
}

// TestCLIExitCodes pins the process contract: 0 on success, 1 on drift or an
// I/O failure, 2 on a usage error. `make generated-check` distinguishes them
// only by the exit code.
func TestCLIExitCodes(t *testing.T) {
	dir := t.TempDir()

	var stderr strings.Builder
	if code := cli([]string{"-out", dir}, &stderr); code != 0 {
		t.Fatalf("write mode exited %d: %s", code, stderr.String())
	}
	if _, err := os.Stat(artifactPath(dir)); err != nil {
		t.Fatalf("write mode produced no artifact: %v", err)
	}

	stderr.Reset()
	if code := cli([]string{"-out", dir, "-check"}, &stderr); code != 0 {
		t.Fatalf("check mode exited %d against fresh bytes: %s", code, stderr.String())
	}

	stderr.Reset()
	if err := os.WriteFile(artifactPath(dir), []byte("stale"), 0o644); err != nil {
		t.Fatalf("write stale: %v", err)
	}
	if code := cli([]string{"-out", dir, "-check"}, &stderr); code != 1 {
		t.Fatalf("check mode exited %d against a stale artifact, want 1", code)
	}
	if !strings.Contains(stderr.String(), apicontract.RegenerateCommand) {
		t.Fatalf("the failure did not reach stderr: %q", stderr.String())
	}

	stderr.Reset()
	if code := cli([]string{"-nonsense"}, &stderr); code != 2 {
		t.Fatalf("an unknown flag exited %d, want 2", code)
	}
	if stderr.Len() == 0 {
		t.Fatal("a usage error printed nothing")
	}
}

// TestCLIDefaultsToTheDocsDirectory documents the default an operator relies on
// when running the generator by hand from the repository root.
func TestCLIDefaultsToTheDocsDirectory(t *testing.T) {
	var stderr strings.Builder
	// Check mode against the real committed artifact: it must already be
	// current, which also proves the default -out value points at it.
	t.Chdir("../../..")
	if code := cli([]string{"-check"}, &stderr); code != 0 {
		t.Fatalf("check mode against the default output directory exited %d: %s", code, stderr.String())
	}
}
