// Copyright 2026 Victor Niharra <vniharrafe@gmail.com>
// SPDX-License-Identifier: agpl

// Command apicontractgen writes the generated external API contract:
// docs/generated/openapi.json (ADR 0019 §29).
//
//	go generate ./internal/apicontract   # or: make api-contract-generate
//	make generated-check                 # check mode; writes nothing
//
// Generation is deterministic: sorted, no timestamp, no absolute path, no
// map-iteration order, no network access, byte-identical across clean
// checkouts. Check mode never writes, so it can run in CI against a read-only
// tree and still leave `git status` clean.
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"jul/internal/apicontract"
)

func main() {
	out := flag.String("out", "docs", "directory that receives the generated artifact")
	check := flag.Bool("check", false, "compare the generated bytes with the file on disk and write nothing")
	flag.Parse()

	if err := run(*out, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(outDir string, check bool) error {
	want, err := apicontract.Generate()
	if err != nil {
		return fmt.Errorf("apicontractgen: %w", err)
	}
	path := filepath.Join(outDir, filepath.FromSlash(apicontract.ArtifactPath))

	if check {
		got, err := os.ReadFile(path)
		switch {
		case errors.Is(err, os.ErrNotExist):
			return staleError(apicontract.ArtifactPath + " (missing)")
		case err != nil:
			return fmt.Errorf("apicontractgen: read %s: %w", apicontract.ArtifactPath, err)
		case string(got) != string(want):
			return staleError(apicontract.ArtifactPath)
		}
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("apicontractgen: create directory for %s: %w", apicontract.ArtifactPath, err)
	}
	if err := os.WriteFile(path, want, 0o644); err != nil {
		return fmt.Errorf("apicontractgen: write %s: %w", apicontract.ArtifactPath, err)
	}
	return nil
}

func staleError(what string) error {
	return fmt.Errorf(
		"apicontractgen: the generated external API contract is stale: %s\n"+
			"    it is rendered from the admin route catalog and the Go DTOs, and is never hand-edited.\n"+
			"    run: %s",
		what, apicontract.RegenerateCommand)
}
