//go:build importer

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"jul/internal/config"
)

func writeNginx(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "nginx.conf")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write nginx.conf: %v", err)
	}
	return path
}

const sampleNginx = `
http {
  upstream app {
    server 10.0.0.1:8080 weight=2;
    server 10.0.0.2:8080;
  }
  server {
    listen 80;
    server_name example.com;
    location / {
      proxy_pass http://app;
    }
    location /static {
      root /var/www;
    }
  }
}
`

func TestCmdImportNginxToFile(t *testing.T) {
	in := writeNginx(t, sampleNginx)
	out := filepath.Join(t.TempDir(), "jul.toml")
	code, _, errOut := capture(t, func() int {
		return cmdImport([]string{"nginx", "-o", out, in})
	})
	if code != 0 {
		t.Fatalf("exit = %d, want 0\nstderr:\n%s", code, errOut)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	cfg, err := config.Parse(data)
	if err != nil {
		t.Fatalf("generated config does not parse:\n%s\nerror: %v", data, err)
	}
	if err := config.Validate(cfg); err != nil {
		t.Fatalf("generated config does not validate: %v", err)
	}
	if !strings.Contains(string(data), "Generated by") {
		t.Errorf("expected a generated-by header comment:\n%s", data)
	}
	if !strings.Contains(errOut, "imported") {
		t.Errorf("expected an import summary on stderr:\n%s", errOut)
	}
}

func TestCmdImportNginxToStdout(t *testing.T) {
	in := writeNginx(t, sampleNginx)
	code, out, _ := capture(t, func() int {
		return cmdImport([]string{"nginx", in})
	})
	if code != 0 {
		t.Fatalf("exit = %d, want 0", code)
	}
	if _, err := config.Parse([]byte(out)); err != nil {
		t.Errorf("stdout is not valid TOML: %v\n%s", err, out)
	}
}

func TestCmdImportUnknownSource(t *testing.T) {
	code, _, errOut := capture(t, func() int {
		return cmdImport([]string{"apache", "x.conf"})
	})
	if code != 1 {
		t.Errorf("exit = %d, want 1", code)
	}
	if !strings.Contains(errOut, "unknown import source") {
		t.Errorf("expected an unknown-source error:\n%s", errOut)
	}
}

func TestCmdImportMissingFile(t *testing.T) {
	code, _, _ := capture(t, func() int {
		return cmdImport([]string{"nginx"})
	})
	if code != 1 {
		t.Errorf("exit = %d, want 1", code)
	}
}
