// Copyright 2026 Victor Niharra <vniharrafe@gmail.com>
// SPDX-License-Identifier: agpl

//go:build importer

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"jul/internal/config"
)

func writeNginx(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "nginx.conf")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write nginx.conf: %v", err)
	}
	return path
}

const sampleNginx = `
http {
  upstream app {
    server 10.0.0.1:8080 weight=2;
    server 10.0.0.2:8080;
  }
  server {
    listen 80;
    server_name example.com;
    location / {
      proxy_pass http://app;
    }
    location /static {
      root /var/www;
    }
  }
}
`

func TestCmdImportNginxToFile(t *testing.T) {
	in := writeNginx(t, sampleNginx)
	out := filepath.Join(t.TempDir(), "jul.toml")
	code, _, errOut := capture(t, func() int {
		return cmdImport([]string{"nginx", "-o", out, in})
	})
	if code != 0 {
		t.Fatalf("exit = %d, want 0\nstderr:\n%s", code, errOut)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	cfg, err := config.Parse(data)
	if err != nil {
		t.Fatalf("generated config does not parse:\n%s\nerror: %v", data, err)
	}
	if err := config.Validate(cfg); err != nil {
		t.Fatalf("generated config does not validate: %v", err)
	}
	if !strings.Contains(string(data), "Generated by") {
		t.Errorf("expected a generated-by header comment:\n%s", data)
	}
	if !strings.Contains(errOut, "imported") {
		t.Errorf("expected an import summary on stderr:\n%s", errOut)
	}
}

func TestCmdImportNginxToStdout(t *testing.T) {
	in := writeNginx(t, sampleNginx)
	code, out, _ := capture(t, func() int {
		return cmdImport([]string{"nginx", in})
	})
	if code != 0 {
		t.Fatalf("exit = %d, want 0", code)
	}
	if _, err := config.Parse([]byte(out)); err != nil {
		t.Errorf("stdout is not valid TOML: %v\n%s", err, out)
	}
}

func TestCmdImportUnknownSource(t *testing.T) {
	code, _, errOut := capture(t, func() int {
		return cmdImport([]string{"apache", "x.conf"})
	})
	if code != importExitUsage {
		t.Errorf("exit = %d, want %d", code, importExitUsage)
	}
	if !strings.Contains(errOut, "unknown import source") {
		t.Errorf("expected an unknown-source error:\n%s", errOut)
	}
}

func TestCmdImportMissingFile(t *testing.T) {
	code, _, _ := capture(t, func() int {
		return cmdImport([]string{"nginx"})
	})
	if code != importExitUsage {
		t.Errorf("exit = %d, want %d", code, importExitUsage)
	}
}

// goldenImportPath is the byte-stable reference output for the sampleNginx
// input. Regenerate intentionally with UPDATE_IMPORT_GOLDEN=1 after a
// purposeful change to the translator's output format.
const goldenImportPath = "testdata/import-nginx-golden.toml"

// TestCmdImportNginxGolden asserts that the canonical TOML produced by
// "jul import nginx" for the sample fixture is byte-stable. This catches
// unintentional drift in marshalling, field ordering, or comment formatting.
// Run with UPDATE_IMPORT_GOLDEN=1 to regenerate the golden file after a
// deliberate change to the translator output.
func TestCmdImportNginxGolden(t *testing.T) {
	in := writeNginx(t, sampleNginx)

	code, got, errOut := capture(t, func() int {
		return cmdImport([]string{"nginx", in})
	})
	if code != 0 {
		t.Fatalf("import exit = %d, want 0\nstderr:\n%s", code, errOut)
	}

	// The first comment line embeds the input file path, which varies per
	// machine and temp-dir invocation. Replace it with a fixed placeholder so
	// the golden is byte-stable across environments.
	normalize := func(s string) string {
		lines := strings.Split(s, "\n")
		for i, l := range lines {
			if strings.HasPrefix(l, "# Generated by") {
				lines[i] = "# Generated by `jul import nginx` from <path>"
			}
		}
		return strings.Join(lines, "\n")
	}
	got = normalize(got)

	if os.Getenv("UPDATE_IMPORT_GOLDEN") == "1" {
		if err := os.MkdirAll(filepath.Dir(goldenImportPath), 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(goldenImportPath, []byte(got), 0o600); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("golden file updated: %s", goldenImportPath)
	}

	want, err := os.ReadFile(goldenImportPath)
	if err != nil {
		t.Fatalf("read golden (run with UPDATE_IMPORT_GOLDEN=1 to seed): %v", err)
	}
	// Normalise line endings so the comparison is CRLF-safe on Windows.
	wantNorm := normalize(strings.ReplaceAll(string(want), "\r\n", "\n"))
	if got != wantNorm {
		t.Fatalf("import output differs from golden.\n"+
			"Run `UPDATE_IMPORT_GOLDEN=1 go test -tags importer ./cmd/jul/ -run TestCmdImportNginxGolden` to update.\n"+
			"--- got (first 512 chars) ---\n%.512s\n--- want (first 512 chars) ---\n%.512s",
			got, wantNorm)
	}
}
