// Copyright 2026 Victor Niharra <vniharrafe@gmail.com>
// SPDX-License-Identifier: agpl

//go:build importer

package nginx

import (
	"fmt"
	"sort"
	"strings"

	ngx "github.com/tufanbarisyildirim/gonginx/config"
)

// Finding records a directive that could not be translated, with the source
// line so the operator can find and port it by hand.
type Finding struct {
	Line   int
	Name   string
	Reason string
}

// Report summarizes a translation: what was produced and what needs manual
// attention. It is never silent — every directive the translator did not map is
// captured in Skipped, and every lossy mapping is captured in Notes.
type Report struct {
	Source     string
	Servers    int
	Upstreams  int
	Locations  int
	Skipped    []Finding
	Notes      []string
	Assessment *Assessment
}

// skip records an unsupported directive from the parse tree.
func (r *Report) skip(d ngx.IDirective, reason string) {
	r.skipNamed(d.GetName(), d.GetLine(), reason)
}

// skipNamed records an unsupported directive by an explicit name (used when a
// more descriptive label than the bare directive name is helpful, e.g. a named
// location).
func (r *Report) skipNamed(name string, line int, reason string) {
	r.Skipped = append(r.Skipped, Finding{Line: line, Name: name, Reason: reason})
}

// note records an informational message about a lossy or approximate mapping.
func (r *Report) note(format string, args ...any) {
	r.Notes = append(r.Notes, fmt.Sprintf(format, args...))
}

// Header returns a TOML comment block to prepend to the generated config. It
// credits the source and lists every skipped directive as a TODO so the
// untranslated parts are visible in the output file itself, not only in the
// console report.
func (r *Report) Header() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `jul import nginx` from %s\n", r.Source)
	fmt.Fprintf(&b, "# Translated %d server(s), %d upstream(s), %d location(s).\n", r.Servers, r.Upstreams, r.Locations)
	if len(r.Skipped) > 0 {
		b.WriteString("#\n# The following directives were NOT translated - review and port them manually:\n")
		for _, f := range r.sortedSkipped() {
			fmt.Fprintf(&b, "#   TODO line %d: %s - %s\n", f.Line, f.Name, f.Reason)
		}
	}
	if len(r.Notes) > 0 {
		b.WriteString("#\n# Notes:\n")
		for _, n := range r.Notes {
			fmt.Fprintf(&b, "#   - %s\n", n)
		}
	}
	return b.String()
}

// Summary returns a human-readable report for the console (stderr).
func (r *Report) Summary() string {
	var b strings.Builder
	fmt.Fprintf(&b, "imported %s: %d server(s), %d upstream(s), %d location(s)\n",
		r.Source, r.Servers, r.Upstreams, r.Locations)
	if len(r.Skipped) > 0 {
		fmt.Fprintf(&b, "\n%d directive(s) not translated (port manually):\n", len(r.Skipped))
		for _, f := range r.sortedSkipped() {
			fmt.Fprintf(&b, "  line %d: %s - %s\n", f.Line, f.Name, f.Reason)
		}
	}
	if len(r.Notes) > 0 {
		b.WriteString("\nnotes:\n")
		for _, n := range r.Notes {
			fmt.Fprintf(&b, "  - %s\n", n)
		}
	}
	return b.String()
}

// sortedSkipped returns the skipped findings ordered by source line for stable,
// readable output.
func (r *Report) sortedSkipped() []Finding {
	out := make([]Finding, len(r.Skipped))
	copy(out, r.Skipped)
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Line != out[j].Line {
			return out[i].Line < out[j].Line
		}
		return out[i].Name < out[j].Name
	})
	return out
}
