import re

with open('test-full.toml', 'r', encoding='utf-8') as f:
    lines = f.readlines()

output = []
for line in lines:
    # Remove inline error_pages (generated by Python script)
    if line.strip().startswith('error_pages = {'):
        continue
    # Fix verify_san inline table
    if 'verify_san = { dns =' in line:
        output.append('    # verify_san = ["localhost"]  # string list\n')
        continue
    output.append(line)

with open('test-full.toml', 'w', encoding='utf-8') as f:
    f.writelines(output)

print('OK')
