#!/usr/bin/env python3
from pathlib import Path

DOC_LINK = "See [Admin runtime hot reload (HR-06B)](admin-runtime-hot-reload.md) for the complete request-generation, Prepare/Publish, rollback and filesystem-safety contract."

sections = {
    "docs/console.md": f'''\n\n## Hot Console mode (HR-06B)\n\nIn Full builds, `[admin].console` is hot-reloadable on an already-running admin server. The route mux and admin listener stay in place: each request is pinned to one immutable admin generation and `/`/`/ui` dispatches either the embedded Console or the fallback admin UI from that generation. Turning the Console off therefore does **not** disable authenticated admin APIs. Lean builds report the Console as not compiled/effective and continue to use the fallback UI even when the configured flag is true.\n\nThe Runtime settings drawer submits a typed change through the normal lifecycle preview/apply ledger. Disabling the web Console requires an explicit acknowledgement and shows the recovery path before apply: set `[admin] console = true` in the source configuration and reload, or use an authenticated configuration apply/patch API request. The UI waits for the correlated terminal apply result before relying on the Console remaining reachable. `admin.enabled` and `admin.listen` are intentionally not part of this capability and remain restart-required under #97.\n\n{DOC_LINK}\n''',
    "docs/plugins.md": f'''\n\n## Hot upload policy (HR-06B)\n\n`[admin].plugin_upload_enabled`, `plugin_upload_max_size` and `plugin_upload_dir` are hot-reloadable on an existing admin server. A request captures all three values once before multipart processing. If uploads are disabled, Jul rejects the request with `403` **before reading the request body**. Tightening/loosening the size cap or switching directories affects new requests after Publish; an upload already in flight finishes under the generation that admitted it.\n\nChanging directory `A → B` does not migrate, copy or delete plugin files. Disabling uploads also leaves existing files intact and does not activate/deactivate plugins: activation remains configuration-driven. Candidate storage is checked before Publish with reversible probes that do not create the configured final directory. Request writes are confined with `os.Root`, use owner-only temporary/final files on Unix, reject symlink/special-file destinations and retain atomic replacement semantics.\n\n{DOC_LINK}\n''',
    "docs/reload-semantics.md": f'''\n\n## HR-06B admin operational generation\n\n`admin.console`, `admin.plugin_upload_enabled`, `admin.plugin_upload_max_size` and `admin.plugin_upload_dir` are `hot_reload` after #157. They publish together with the existing immutable admin authentication/RBAC snapshot, and the outer admin handler pins that single snapshot once per request. Authentication, Console dispatch, upload admission/limit/directory and safe projections cannot mix generations inside one request.\n\nUpload directory preparation occurs before Publish and is reversible. A preparation failure leaves the previous live generation untouched. `admin.enabled` and `admin.listen` remain structural `restart_required` fields; a mixed candidate changing either one is not partially hot-applied. The generated lifecycle registry remains authoritative.\n\n{DOC_LINK}\n''',
    "docs/security-posture.md": f'''\n\n## Admin runtime generation and upload boundary (HR-06B)\n\nConsole mode and plugin-upload policy now share the same immutable per-request admin generation as authentication/RBAC. This closes a split-generation class where a request could otherwise authenticate under one policy and later consult another mutable Console/upload policy. Upload-disable rejects before body parsing; candidate directories are preflighted before Publish; final writes are root-confined, owner-only on Unix and reject unsafe destination types.\n\nRuntime observability exposes only bounded categories and effective state. Upload paths, filenames, bearer tokens, resolved secrets and raw filesystem errors are not metric labels or runtime-status fields. The configured upload directory appears only on the authenticated `config:read` settings projection where it is required for operator editing.\n\n{DOC_LINK}\n''',
    "docs/known-limitations.md": f'''\n\n## Admin operational hot-reload boundaries\n\nHR-06B hot-reloads Console mode and plugin-upload admission/max-size/directory only when the admin server already exists. It does **not** make the management listener structural lifecycle dynamic: `admin.enabled` and `admin.listen` still require the established restart/stage-restart path, pending the separately gated #97 decision.\n\nPlugin directory changes intentionally do not migrate or clean up files. Host-filesystem semantics still apply outside the opened upload root, and a storage device can fail after a candidate was successfully prepared; such post-Publish I/O failures are reported as runtime degradation/rejection rather than pretending the committed configuration was rolled back. A lean binary cannot serve embedded Console assets even if `admin.console = true`; effective status reports that distinction explicitly.\n\n{DOC_LINK}\n''',
    "docs/configuration.md": f'''\n\n## Admin Console/upload reloadability\n\nOn a running admin server, `admin.console`, `admin.plugin_upload_enabled`, `admin.plugin_upload_max_size` and `admin.plugin_upload_dir` are hot-reloadable. They are published as one immutable request-generation policy with admin authentication/RBAC. The upload directory is preflighted before Publish; changing it does not migrate files. `admin.enabled` and `admin.listen` remain restart-required.\n\n{DOC_LINK}\n''',
    "SECURITY.md": '''\n\n## Admin Console and plugin-upload hot reload\n\nHR-06B (#157) treats admin authentication/RBAC, Console dispatch and plugin-upload policy as one immutable per-request generation. Disabling uploads rejects before request-body parsing; candidate upload storage is validated before Publish with reversible probes; admitted writes are confined to an `os.Root`, use owner-only files on Unix, and reject symbolic-link/special-file final destinations. Bounded runtime diagnostics do not expose upload paths, filenames, bearer tokens or resolved secrets as metric labels/status fields. See [`docs/admin-runtime-hot-reload.md`](docs/admin-runtime-hot-reload.md) for the complete security and concurrency contract.\n''',
}

for path, section in sections.items():
    p = Path(path)
    text = p.read_text()
    marker = section.strip().splitlines()[0]
    if marker not in text:
        p.write_text(text.rstrip() + section + "\n")

p = Path("CHANGELOG.md")
text = p.read_text()
entry = '''- **Admin Console and plugin-upload policy hot-reload safely (#157 / HR-06B).** `admin.console`, `admin.plugin_upload_enabled`, `admin.plugin_upload_max_size` and `admin.plugin_upload_dir` now publish with the existing immutable admin authentication/RBAC snapshot and are pinned once per request by the stable mux. Console `on → off → on` no longer rebuilds routes or the listener; lean builds remain truthfully fallback-only. Upload disable rejects before multipart body reads, size/directory policy is captured for the whole request, candidate storage is reversibly preflighted before Publish, and final writes use `os.Root` confinement with owner-only atomic replacement and symlink/special-file rejection. Directory changes never migrate/delete files and in-flight A requests stay on A. The Console gains a `config:read` safe projection plus narrow typed Console/upload settings edits, lifecycle preview, explicit self-disable recovery acknowledgement and no-migration/no-delete guidance. Runtime status exposes bounded compiled/configured/effective/upload-health/rejection/preparation categories without paths, filenames or secrets. The exact four fields move to `hot_reload`; `admin.enabled`/`admin.listen` remain restart-bound under #97. See `docs/admin-runtime-hot-reload.md`.\n'''
if entry not in text:
    marker = "### Added\n"
    if marker not in text:
        raise SystemExit("CHANGELOG Added heading not found")
    text = text.replace(marker, marker + entry, 1)
    p.write_text(text)
